version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_pass
      POSTGRES_DB:finance_dwh
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.airflow
    restart: always
    environment:
      # Point Airflow 3.0.1 to Postgres
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/raw_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # Disable user prompts
      AIRFLOW__METASTORE__MIN_SERIALIZED_DAG_VERSION: "5"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
